// let questions = [
//   {
//       question: "The Harvard architecture for micro-controllers added which additional bus?",
//       choice1: "Instruction",
//       choice2: "Address",
//       choice3: "Data",
//       choice4: "Control",
//       answer: 1,
//   },
//   {
//       question: "When was the first Call of Duty title released?",
//       choice1: "December 1, 2003",
//       choice2: "November 14, 2002",
//       choice3: "July 18, 2004",
//       choice4: "October 29, 2003",
//       answer: 4,
//   },
//   {
//       question: "Which Elton John hit starts with the line 'When are you gonna come down' ?",
//       choice1: "Rocket Man",
//       choice2: "Goodbye Yellow Brick Road",
//       choice3: "Bennie and the Jets",
//       choice4: "Crocodile Rock",
//       answer: 2,
//   },
//   {
//       question: "The Internet Meme 'All your base are belong to us' is based on the poorly translated English Version of which Video Game?",
//       choice1: "Zero Wing",
//       choice2: "F-Zero",
//       choice3: "Wing Commander",
//       choice4: "Star Wars: X-Wing",
//       answer: 1,
//   },
//   {
//       question: "What was the nickname of the original model for Half-Life's protagonist Gordon Freeman?",
//       choice1: "Gordon the Space Biker",
//       choice2: "Ivan the Alien Biker",
//       choice3: "Ivan the Space Biker",
//       choice4: "Gordon the Alien Biker",
//       answer: 3,
//   },
//   {
//       question: "When was YouTube founded?",
//       choice1: "February 14, 2005",
//       choice2: "May 22, 2004",
//       choice3: "March 22, 2005",
//       choice4: "June 22, 2004",
//       answer: 1,
//   },
//   {
//       question: "The mountainous Khyber Pass connects which of the two following countries?",
//       choice1: "Afghanistan and Pakistan",
//       choice2: "India and Nepal",
//       choice3: "Pakistan and India",
//       choice4: "Tajikistan and Kyrgyzstan",
//       answer: 1,
//   },
//   {
//       question: "What is isobutylphenylpropanoic acid more commonly known as?",
//       choice1: "Morphine",
//       choice2: "Aspirin",
//       choice3: "Ketamine",
//       choice4: "Ibuprofen",
//       answer: 4,
//   },
//   {
//       question: "Which of these songs is not by Tatsuro Yamashita?",
//       choice1: "Merry-Go Round",
//       choice2: "Lucky Lady Feel So Good",
//       choice3: "Let's Dance Baby",
//       choice4: "Love Talking",
//       answer: 2,
//   },
//   {
//       question: "Which of these was the name of a bug found in April 2014 in the publicly available OpenSSL cryptography library?",
//       choice1: "ShellShock",
//       choice2: "Corrupted Blood",
//       choice3: "ShellScript",
//       choice4: "Heartbleed",
//       answer: 4,
//   },
// ];